/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author nicol
 */
public class IGMain extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public IGMain() {
        initComponents();
        setExtendedState(this.MAXIMIZED_BOTH);
        buttonGroupDonnes.add(jRadioButtonValAle);
        buttonGroupDonnes.add(jRadioButtonValChoisies);
        
        jTextFieldID.setText("HEY");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDonnes = new javax.swing.ButtonGroup();
        jSplitPaneSimu = new javax.swing.JSplitPane();
        jScrollPaneSimuResults = new javax.swing.JScrollPane();
        jPanelSimuResults = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelInfosSimu = new javax.swing.JPanel();
        jLabelID = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabelType = new javax.swing.JLabel();
        jComboBoxType = new javax.swing.JComboBox<>();
        jLabelLocalisation = new javax.swing.JLabel();
        jPanelLocalisation = new javax.swing.JPanel();
        jButtonInter = new javax.swing.JButton();
        jButtonExter = new javax.swing.JButton();
        jLabelPort = new javax.swing.JLabel();
        jTextFieldPort = new javax.swing.JTextField();
        jLabelInterval = new javax.swing.JLabel();
        jPanelInterval = new javax.swing.JPanel();
        jLabelMin = new javax.swing.JLabel();
        jSpinnerMin = new javax.swing.JSpinner();
        jLabelMax = new javax.swing.JLabel();
        jSpinnerMaxi = new javax.swing.JSpinner();
        jLabelFreq = new javax.swing.JLabel();
        jSpinnerFreq = new javax.swing.JSpinner();
        jLabelDonnees = new javax.swing.JLabel();
        jPanelDonnees = new javax.swing.JPanel();
        jRadioButtonValAle = new javax.swing.JRadioButton();
        jRadioButtonValChoisies = new javax.swing.JRadioButton();
        jButtonConnect = new javax.swing.JButton();
        jButtonDisconnect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NeoCampus");

        jSplitPaneSimu.setDividerLocation(300);

        jLabel1.setText("Interface de Visualisation");

        javax.swing.GroupLayout jPanelSimuResultsLayout = new javax.swing.GroupLayout(jPanelSimuResults);
        jPanelSimuResults.setLayout(jPanelSimuResultsLayout);
        jPanelSimuResultsLayout.setHorizontalGroup(
            jPanelSimuResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSimuResultsLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel1)
                .addContainerGap(563, Short.MAX_VALUE))
        );
        jPanelSimuResultsLayout.setVerticalGroup(
            jPanelSimuResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSimuResultsLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel1)
                .addContainerGap(703, Short.MAX_VALUE))
        );

        jScrollPaneSimuResults.setViewportView(jPanelSimuResults);

        jSplitPaneSimu.setRightComponent(jScrollPaneSimuResults);

        jPanelInfosSimu.setLayout(new java.awt.GridLayout(8, 2));

        jLabelID.setText("Identificateur du capteur :");
        jPanelInfosSimu.add(jLabelID);
        jPanelInfosSimu.add(jTextFieldID);

        jLabelType.setText("Type de données :");
        jPanelInfosSimu.add(jLabelType);

        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelInfosSimu.add(jComboBoxType);

        jLabelLocalisation.setText("Localisation :");
        jPanelInfosSimu.add(jLabelLocalisation);

        jPanelLocalisation.setLayout(new java.awt.GridLayout(1, 2));

        jButtonInter.setText("Interieur");
        jPanelLocalisation.add(jButtonInter);

        jButtonExter.setText("Exterieur");
        jPanelLocalisation.add(jButtonExter);

        jPanelInfosSimu.add(jPanelLocalisation);

        jLabelPort.setText("Port :");
        jPanelInfosSimu.add(jLabelPort);
        jPanelInfosSimu.add(jTextFieldPort);

        jLabelInterval.setText("Intervalle :");
        jPanelInfosSimu.add(jLabelInterval);

        jPanelInterval.setLayout(new java.awt.GridLayout(2, 2));

        jLabelMin.setText("Min :");
        jPanelInterval.add(jLabelMin);
        jPanelInterval.add(jSpinnerMin);

        jLabelMax.setText("Max :");
        jPanelInterval.add(jLabelMax);
        jPanelInterval.add(jSpinnerMaxi);

        jPanelInfosSimu.add(jPanelInterval);

        jLabelFreq.setText("Fréquence d'envoi :");
        jPanelInfosSimu.add(jLabelFreq);
        jPanelInfosSimu.add(jSpinnerFreq);

        jLabelDonnees.setText("Données :");
        jPanelInfosSimu.add(jLabelDonnees);

        jPanelDonnees.setLayout(new java.awt.GridLayout(2, 1));

        jRadioButtonValAle.setText("Aléatoires");
        jPanelDonnees.add(jRadioButtonValAle);

        jRadioButtonValChoisies.setText("Définies");
        jPanelDonnees.add(jRadioButtonValChoisies);

        jPanelInfosSimu.add(jPanelDonnees);

        jButtonConnect.setText("Connexion");
        jPanelInfosSimu.add(jButtonConnect);

        jButtonDisconnect.setText("Deconnexion");
        jPanelInfosSimu.add(jButtonDisconnect);

        jSplitPaneSimu.setLeftComponent(jPanelInfosSimu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneSimu, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneSimu, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDonnes;
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonDisconnect;
    private javax.swing.JButton jButtonExter;
    private javax.swing.JButton jButtonInter;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDonnees;
    private javax.swing.JLabel jLabelFreq;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelInterval;
    private javax.swing.JLabel jLabelLocalisation;
    private javax.swing.JLabel jLabelMax;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JPanel jPanelDonnees;
    private javax.swing.JPanel jPanelInfosSimu;
    private javax.swing.JPanel jPanelInterval;
    private javax.swing.JPanel jPanelLocalisation;
    private javax.swing.JPanel jPanelSimuResults;
    private javax.swing.JRadioButton jRadioButtonValAle;
    private javax.swing.JRadioButton jRadioButtonValChoisies;
    private javax.swing.JScrollPane jScrollPaneSimuResults;
    private javax.swing.JSpinner jSpinnerFreq;
    private javax.swing.JSpinner jSpinnerMaxi;
    private javax.swing.JSpinner jSpinnerMin;
    private javax.swing.JSplitPane jSplitPaneSimu;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldPort;
    // End of variables declaration//GEN-END:variables
}
