/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import client.Capteur;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;
import java.util.StringTokenizer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.Plot;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Noémie
 */
public class IPeriode extends javax.swing.JFrame {

    /**
     * Creates new form IPeriode
     */
    
    List<Capteur> listeCapteur = new ArrayList<Capteur>();
    
    
    public IPeriode() {
        initComponents();
        lectureFichHistNomCapteurs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogGraphique = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();
        jLabelAffichage = new javax.swing.JLabel();
        jButtonRetour = new javax.swing.JButton();
        jLabelSelection = new javax.swing.JLabel();
        jComboBoxCapteurSelect = new javax.swing.JComboBox<>();
        jLabelNomCapteur = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDonnees = new javax.swing.JTextArea();
        jButtonGraphique = new javax.swing.JButton();

        jDialogGraphique.setMinimumSize(new java.awt.Dimension(300, 300));

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel3)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel3)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogGraphiqueLayout = new javax.swing.GroupLayout(jDialogGraphique.getContentPane());
        jDialogGraphique.getContentPane().setLayout(jDialogGraphiqueLayout);
        jDialogGraphiqueLayout.setHorizontalGroup(
            jDialogGraphiqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogGraphiqueLayout.setVerticalGroup(
            jDialogGraphiqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelAffichage.setText("Affichage des données du capteur : ");

        jButtonRetour.setText("retour");
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });

        jLabelSelection.setText("Séléction du capteur :");

        jComboBoxCapteurSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Veuillez selectionner un capteur ---" }));
        jComboBoxCapteurSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCapteurSelectActionPerformed(evt);
            }
        });

        jTextAreaDonnees.setEditable(false);
        jTextAreaDonnees.setBackground(new java.awt.Color(240, 240, 240));
        jTextAreaDonnees.setColumns(20);
        jTextAreaDonnees.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDonnees);

        jButtonGraphique.setText("Graphique");
        jButtonGraphique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGraphiqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSelection)
                    .addComponent(jComboBoxCapteurSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabelAffichage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNomCapteur))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 81, Short.MAX_VALUE))
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButtonRetour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGraphique)
                .addGap(54, 54, 54))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabelSelection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxCapteurSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAffichage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomCapteur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRetour)
                    .addComponent(jButtonGraphique))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRetourActionPerformed

    private void jComboBoxCapteurSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCapteurSelectActionPerformed
        String nomCapteur = (String)jComboBoxCapteurSelect.getSelectedItem();
        if (!(nomCapteur.equals("--- Veuillez selectionner un capteur ---"))) {
            jLabelNomCapteur.setText(nomCapteur);
            lectureFichHistDonneesCapteurs(nomCapteur);
        }
    }//GEN-LAST:event_jComboBoxCapteurSelectActionPerformed

    private void jButtonGraphiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGraphiqueActionPerformed
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(1,"v","f");
        dataset.setValue(50,"r","fr");
        
        JFreeChart chart = ChartFactory.createLineChart("Données du capteur", "temps", "valeur", dataset);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.BLUE);
        ChartFrame frame = new ChartFrame("Graphique données",chart);
        frame.setVisible(true);
        frame.setSize(450,450);
        
    }//GEN-LAST:event_jButtonGraphiqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IPeriode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IPeriode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IPeriode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IPeriode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IPeriode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGraphique;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JComboBox<String> jComboBoxCapteurSelect;
    private javax.swing.JDialog jDialogGraphique;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAffichage;
    private javax.swing.JLabel jLabelNomCapteur;
    private javax.swing.JLabel jLabelSelection;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDonnees;
    // End of variables declaration//GEN-END:variables


    public void lectureFichHistNomCapteurs() {
	String fichier = "hist.conf";
	try{
            InputStream ips=new FileInputStream(fichier); 
            InputStreamReader ipsr=new InputStreamReader(ips);
            BufferedReader br=new BufferedReader(ipsr);
            String ligne;
            while ((ligne=br.readLine())!=null){
                jComboBoxCapteurSelect.addItem(ligne);
                while(!(ligne.equals("$"))) ligne=br.readLine();
            }
            br.close(); 
	}		
	catch (Exception e){
            System.out.println(e.toString());
	}
    }
    
    public void lectureFichHistDonneesCapteurs(String nomCapteur) {
	String fichier = "hist.conf",date,val;
	try{
            InputStream ips=new FileInputStream(fichier); 
            InputStreamReader ipsr=new InputStreamReader(ips);
            BufferedReader br=new BufferedReader(ipsr);
            String ligne;
            jTextAreaDonnees.setText("");
            while ((ligne=br.readLine())!=null){
                while (!(ligne.equals(nomCapteur))) ligne=br.readLine();
                ligne=br.readLine();
                if (ligne.equals("e")) jTextAreaDonnees.append("Capteur exterieur.\n");
                else jTextAreaDonnees.append("Capteur intérieur.\n");
                ligne=br.readLine();
                jTextAreaDonnees.append("Localisation : " + ligne + "\n");
                ligne=br.readLine();
                jTextAreaDonnees.append("Type de données mesurées : " + ligne + "\n");
                ligne=br.readLine();
                while(!(ligne.equals("$"))) {
                    StringTokenizer Tok = new StringTokenizer(ligne,";");
                    date = (String) Tok.nextElement();
                    jTextAreaDonnees.append("Date : " + date + "\n");
                    while (Tok.hasMoreElements())  {
                       val = (String) Tok.nextElement();
                       jTextAreaDonnees.append(val + "\n");  
                    }
                    ligne=br.readLine();        
                }
                break;
            }
            br.close(); 
	}		
	catch (Exception e){
            System.out.println(e.toString());
	}
    }
    

}
